# Generated by Django 4.2.10 on 2026-08-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_dailycheckin_today_correct_dailycheckin_today_wrong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='mode',
            field=models.CharField(choices=[('sequential', '顺序背诵'), ('random', '乱序背诵'), ('cover_en', '遮英文'), ('cover_zh', '遮中文'), ('review', '复习'), ('favorite', '收藏复习'), ('exam', '模拟考试')], max_length=20, verbose_name='学习模式'),
        ),
    ]
