# Generated by Django 4.2.10 on 2026-08-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_alter_studysession_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='速记内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quick_memory', to='words.word', verbose_name='单词')),
            ],
            options={
                'verbose_name': '速记',
                'verbose_name_plural': '速记',
            },
        ),
    ]
