# Generated by Django 4.2.10 on 2026-08-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_quickmemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='openai', max_length=50, verbose_name='服务商')),
                ('model_id', models.CharField(max_length=100, verbose_name='模型 ID')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='展示名称')),
                ('base_url', models.CharField(default='https://api.openai.com/v1', max_length=300, verbose_name='接口基础地址')),
                ('endpoint', models.CharField(blank=True, max_length=400, verbose_name='完整请求地址')),
                ('api_key', models.CharField(blank=True, max_length=300, verbose_name='API 密钥')),
                ('context', models.CharField(blank=True, default='128K', max_length=10, verbose_name='上下文')),
                ('vision', models.BooleanField(default=True, verbose_name='支持图片识别')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI 模型',
                'verbose_name_plural': 'AI 模型',
            },
        ),
    ]
