# Generated by Django 4.2.10 on 2026-08-02 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='assistant_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='words.aimodel', verbose_name='小助手模型'),
        ),
    ]
