# Generated by Django 4.2.10 on 2026-08-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_word_meanings_by_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('source', models.CharField(choices=[('image', '图片识别'), ('text', '纯文本'), ('file', '文件导入'), ('manual', '手动添加'), ('command', '命令行导入')], default='text', max_length=20, verbose_name='导入来源')),
                ('unit_number', models.IntegerField(default=99, verbose_name='目标单元编号')),
                ('unit_name', models.CharField(blank=True, max_length=100, verbose_name='单元名称')),
                ('imported_count', models.IntegerField(default=0, verbose_name='成功导入数')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='跳过重复数')),
                ('words_list', models.TextField(default='[]', help_text='JSON格式: ["word1", "word2"]', verbose_name='导入的单词列表')),
            ],
            options={
                'verbose_name': '导入记录',
                'verbose_name_plural': '导入记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
