# Generated by Django 4.2.10 on 2026-08-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_studyprogress_uncommon_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogress',
            name='meaning_attempts',
            field=models.IntegerField(default=0, verbose_name='释义默写次数'),
        ),
        migrations.AddField(
            model_name='studyprogress',
            name='meaning_correct',
            field=models.IntegerField(default=0, verbose_name='释义默写正确次数'),
        ),
        migrations.AddField(
            model_name='studyprogress',
            name='spelling_attempts',
            field=models.IntegerField(default=0, verbose_name='拼写检测次数'),
        ),
        migrations.AddField(
            model_name='studyprogress',
            name='spelling_correct',
            field=models.IntegerField(default=0, verbose_name='拼写正确次数'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='use_ai_meaning_check',
            field=models.BooleanField(default=True, verbose_name='释义默写使用 AI 判定'),
        ),
    ]
