# Generated by Django 4.2.10 on 2026-08-09 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0012_studyprogress_meaning_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='meaning_check_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='words.aimodel', verbose_name='释义默写判定模型'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='quick_memory_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='words.aimodel', verbose_name='速记生成模型'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='recognize_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='words.aimodel', verbose_name='导入识别模型'),
        ),
    ]
