# Generated by Django 4.2.10 on 2026-08-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0013_usersettings_meaning_check_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='review_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='words.aimodel', verbose_name='复审模型'),
        ),
    ]
