# Generated by Django 4.2.10 on 2026-08-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0014_usersettings_review_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachments',
            field=models.JSONField(blank=True, default=list, verbose_name='附件信息'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='会话 ID'),
        ),
    ]
