# Generated by Django 4.2.10 on 2026-08-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0015_chatmessage_attachments_chatmessage_conversation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='新对话', max_length=100, verbose_name='会话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI 会话',
                'verbose_name_plural': 'AI 会话',
                'ordering': ['-updated_at'],
            },
        ),
    ]
