# Generated by Django 4.2.10 on 2026-08-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0016_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogress',
            name='is_excluded',
            field=models.BooleanField(db_index=True, default=False, help_text='标记为永不忘记的词不再出现在背诵/复习中', verbose_name='永不忘记（永久排除）'),
        ),
    ]
