# Generated by Django 4.2.10 on 2026-08-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0017_studyprogress_is_excluded'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='周起始日（周一）')),
                ('week_end', models.DateField(verbose_name='周结束日（周日）')),
                ('summary_json', models.TextField(default='{}', help_text='JSON格式，保存生成时的周期内核心指标', verbose_name='统计数据快照')),
                ('ai_comment', models.TextField(blank=True, default='', verbose_name='AI 评语')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '学习周报',
                'verbose_name_plural': '学习周报',
                'ordering': ['-week_start'],
                'unique_together': {('week_start',)},
            },
        ),
    ]
