# Generated by Django 4.2.10 on 2026-08-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0018_learningreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='自定义背景图片'),
        ),
    ]
