# Generated by Django 4.2.10 on 2026-08-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0019_usersettings_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='batch_size',
            field=models.IntegerField(default=10, verbose_name='每批背诵数量'),
        ),
    ]
