# Generated by Django 4.2.10 on 2026-08-11 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0020_usersettings_batch_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='background_image',
        ),
    ]
