# Generated by Django 4.2.10 on 2026-08-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0021_remove_usersettings_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='gate_answer_release',
            field=models.BooleanField(default=True, verbose_name='高效模式答错后看答案放行'),
        ),
    ]
