# Generated by Django 4.2.10 on 2026-08-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0022_usersettings_gate_answer_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='gate_answer_release',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='gate_answer_show',
            field=models.BooleanField(default=True, verbose_name='高效模式答错后显示答案'),
        ),
    ]
