# Generated by Django 4.2.10 on 2026-08-11 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0023_remove_usersettings_gate_answer_release_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('known', '会'), ('unknown', '不会'), ('spelling_ok', '拼写正确'), ('spelling_wrong', '拼写错误'), ('meaning_ok', '释义正确'), ('meaning_wrong', '释义错误'), ('skip', '永不忘记')], db_index=True, max_length=20, verbose_name='动作')),
                ('source', models.CharField(choices=[('learn', '背诵'), ('review', '复习'), ('favorite', '收藏复习')], db_index=True, default='learn', max_length=20, verbose_name='来源')),
                ('mode', models.CharField(blank=True, default='', max_length=30, verbose_name='模式')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to='words.word', verbose_name='单词')),
            ],
            options={
                'verbose_name': '背词记录',
                'verbose_name_plural': '背词记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
