# Generated by Django 4.2.10 on 2026-08-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0024_studyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='unstable_meanings',
            field=models.TextField(blank=True, default='{}', help_text='按词性记不准的释义，JSON 对象格式 {"n.": ["休息时间"]}', verbose_name='记不准的释义'),
        ),
    ]
