# Generated by Django 4.2.10 on 2026-08-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0025_word_unstable_meanings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='unstable_meanings',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('light', '暖纸浅色'), ('green', '护眼素青'), ('blue', '清爽蓝白'), ('sepia', '复古牛皮'), ('dark', '深夜书桌'), ('nightblue', '星空午夜')], default='light', max_length=15, verbose_name='主题'),
        ),
    ]
