# Generated by Django 4.2.10 on 2026-08-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0026_remove_word_unstable_meanings_usersettings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogress',
            name='manual_level',
            field=models.IntegerField(choices=[(1, '熟练'), (2, '次于熟练'), (3, '生词')], db_index=True, default=3, help_text='1=熟练 2=次于熟练 3=生词；与自动「会/不会」双轨并存，由用户手动划分', verbose_name='手动等级'),
        ),
    ]
