# Generated by Django 4.2.10 on 2026-08-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0027_studyprogress_manual_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('file', models.FileField(upload_to='pdfs/', verbose_name='PDF 文件')),
                ('filesize', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': 'PDF 资料',
                'verbose_name_plural': 'PDF 资料',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
