# Generated by Django 4.2.10 on 2026-08-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0028_pdf_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='用于去重，相同内容判定为重复', max_length=32, verbose_name='文件MD5'),
        ),
    ]
