# Generated by Django 4.2.10 on 2026-08-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0029_pdf_filehash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('video_file', models.FileField(upload_to='music/videos/', verbose_name='视频文件')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='music/audio/', verbose_name='音频文件')),
                ('duration', models.FloatField(default=0, verbose_name='时长(秒)')),
                ('filesize', models.BigIntegerField(default=0, verbose_name='视频大小(字节)')),
                ('transcode_status', models.CharField(choices=[('pending', '转码中'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=10, verbose_name='转码状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('light', '暖纸浅色'), ('blue', '清爽蓝白'), ('sepia', '复古牛皮'), ('dark', '深夜书桌'), ('nightblue', '星空午夜')], default='light', max_length=15, verbose_name='主题'),
        ),
    ]
