# Generated by Django 4.2.10 on 2026-08-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0030_music_alter_usersettings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='transcode_error',
            field=models.TextField(blank=True, default='', verbose_name='转码错误信息'),
        ),
    ]
