# Generated by Django 4.2.10 on 2026-08-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0031_music_transcode_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogress',
            name='consecutive_correct',
            field=models.IntegerField(default=0, help_text='背诵/复习中连续答对计数，达到阈值自动标记为永不忘记', verbose_name='连续答对次数'),
        ),
    ]
