# Generated by Django 4.2.10 on 2026-08-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0032_studyprogress_consecutive_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='预设名称')),
                ('preset_type', models.CharField(choices=[('learn', '背诵'), ('review', '复习')], max_length=10, verbose_name='类型')),
                ('params', models.JSONField(default=dict, verbose_name='参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学习预设',
                'verbose_name_plural': '学习预设',
                'ordering': ['-created_at'],
            },
        ),
    ]
