# Generated by Django 4.2.10 on 2026-08-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0033_studypreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('light', '暖纸浅色'), ('blue', '清爽蓝白'), ('sepia', '复古牛皮'), ('dark', '深夜书桌'), ('nightblue', '星空午夜'), ('custom', '自定义壁纸')], default='light', max_length=15, verbose_name='主题'),
        ),
    ]
