# Generated by Django 4.2.10 on 2026-08-18 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0034_alter_usersettings_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='年份')),
                ('exam_type', models.CharField(choices=[('english1', '英语一'), ('english2', '英语二')], max_length=10, verbose_name='考试类型')),
                ('question_type', models.CharField(choices=[('small_essay', '小作文'), ('big_essay', '大作文'), ('translation', '翻译')], max_length=20, verbose_name='题型')),
                ('genre', models.CharField(blank=True, default='', help_text='小作文：书信/通知/道歉/邀请…；大作文：图画/图表', max_length=50, verbose_name='体裁')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='题目内容')),
                ('prompt', models.TextField(blank=True, default='', verbose_name='写作要求/题干')),
                ('model_answer', models.TextField(blank=True, default='', verbose_name='参考范文/参考译文')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='主题标签')),
                ('difficulty', models.IntegerField(default=3, verbose_name='难度(1-5)')),
                ('is_imported', models.BooleanField(default=True, verbose_name='已入库')),
            ],
            options={
                'verbose_name': '考研真题',
                'verbose_name_plural': '考研真题',
                'ordering': ['exam_type', '-year', 'question_type'],
                'unique_together': {('exam_type', 'year', 'question_type')},
            },
        ),
        migrations.CreateModel(
            name='WritingPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('essay', '作文'), ('translation', '翻译')], default='essay', max_length=20, verbose_name='练习类型')),
                ('source', models.CharField(default='ai', help_text='ai=AI代写, manual=手动写作, translation=翻译练习', max_length=20, verbose_name='来源')),
                ('user_input', models.TextField(blank=True, default='', verbose_name='用户作答')),
                ('ai_output', models.TextField(blank=True, default='', verbose_name='AI 范文/译文')),
                ('score_json', models.TextField(blank=True, default='{}', help_text='JSON 格式，各维度评分与建议', verbose_name='批改评分数据')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='AI 批改意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='words.examquestion', verbose_name='真题')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '写作练习',
                'verbose_name_plural': '写作练习',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField(verbose_name='好句/错误句子')),
                ('meaning', models.TextField(blank=True, default='', verbose_name='释义/修改建议')),
                ('phrase_type', models.CharField(choices=[('nice', '好句'), ('error', '错误点'), ('replace', '替换表达')], default='nice', max_length=20, verbose_name='类型')),
                ('is_collected', models.BooleanField(default=True, verbose_name='已收藏')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phrases', to='words.writingpractice', verbose_name='来源练习')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '写作好句',
                'verbose_name_plural': '写作好句',
                'ordering': ['-created_at'],
            },
        ),
    ]
