# Generated by Django 4.2.10 on 2026-08-18 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0035_examquestion_writingpractice_writingphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='exam_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='words.aimodel', verbose_name='考研写作工坊模型'),
        ),
    ]
