# Generated by Django 4.2.10 on 2026-08-18 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0036_usersettings_exam_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='exam_generate', max_length=40, verbose_name='调用功能')),
                ('model_id', models.CharField(blank=True, default='', max_length=120, verbose_name='模型')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(毫秒)')),
                ('prompt_preview', models.TextField(blank=True, default='', help_text='记录提示词前 500 字，便于追溯', verbose_name='提示词预览')),
                ('response_preview', models.TextField(blank=True, default='', help_text='记录响应前 500 字', verbose_name='响应预览')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='调用时间')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_calls', to='words.writingpractice', verbose_name='关联练习')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI 调用日志',
                'verbose_name_plural': 'AI 调用日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
