# Generated by Django 4.2.10 on 2026-08-18 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0037_aicalllog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingpractice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='words.examquestion', verbose_name='真题'),
        ),
    ]
