# Generated by Django 4.2.10 on 2026-08-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0038_alter_writingpractice_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='exam_type',
            field=models.CharField(choices=[('english1', '英语一'), ('english2', '英语二'), ('cet6', '六级')], max_length=10, verbose_name='考试类型'),
        ),
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together={('exam_type', 'year', 'question_type', 'genre')},
        ),
    ]
